export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://api.annayog.app/v1';
export const WS_URL = import.meta.env.VITE_WS_URL || 'wss://api.annayog.app/v1/ws';
export const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID || '';

export const ROLES = {
  RESTAURANT: 'RESTAURANT',
  INDIVIDUAL_DONOR: 'INDIVIDUAL_DONOR',
  NGO: 'NGO',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  ADMIN: 'ADMIN',
};

export const VERIFICATION_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  RESUBMIT_REQUIRED: 'RESUBMIT_REQUIRED',
};

export const LISTING_STATUS = {
  LISTED: 'LISTED',
  MATCHED_PENDING_NGO_ACCEPT: 'MATCHED_PENDING_NGO_ACCEPT',
  NGO_ACCEPTED: 'NGO_ACCEPTED',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  PARTNER_ARRIVED_PICKUP: 'PARTNER_ARRIVED_PICKUP',
  PICKED_UP: 'PICKED_UP',
  DELIVERED: 'DELIVERED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
};

export const PERISHABILITY = {
  HIGHLY_PERISHABLE: 'HIGHLY_PERISHABLE',
  MODERATE: 'MODERATE',
  PACKAGED_SHELF_STABLE: 'PACKAGED_SHELF_STABLE',
};

export const VEHICLE_TYPES = {
  BIKE: 'BIKE',
  ON_FOOT: 'ON_FOOT',
  CAR: 'CAR',
};
